"""
Audio Embedding Generation Module

Handles audio embedding generation using AudioCLIP and other audio models.
"""

import logging
from typing import List, Optional, Union, Dict, Any
from pathlib import Path
import numpy as np

logger = logging.getLogger(__name__)

try:
    import torch
    import torchaudio
    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False
    torch = None
    torchaudio = None
    logger.warning("PyTorch/TorchAudio not available. Install with: pip install torch torchaudio")

try:
    from transformers import AutoProcessor, AutoModel
    TRANSFORMERS_AVAILABLE = True
except ImportError:
    TRANSFORMERS_AVAILABLE = False
    logger.warning("Transformers library not available. Install with: pip install transformers")

# AudioCLIP is not directly available via transformers, so we'll use a compatible alternative
# For production, consider using wav2vec2 or similar models that are well-supported
AUDIOCLIP_AVAILABLE = False
try:
    # Try to import AudioCLIP (if available via custom installation)
    # For now, we'll use wav2vec2 as a practical alternative
    from transformers import Wav2Vec2Processor, Wav2Vec2Model
    AUDIO_MODEL_AVAILABLE = True
except ImportError:
    AUDIO_MODEL_AVAILABLE = False
    logger.warning("Audio models not available. Install with: pip install transformers torchaudio")


class AudioEmbeddingGenerator:
    """
    Base class for audio embedding generation
    """
    
    def __init__(self, model_name: str = "facebook/wav2vec2-base-960h"):
        """
        Initialize audio embedding generator
        
        Args:
            model_name: Name of the audio model to use (default: wav2vec2)
        """
        self.model_name = model_name
        self.model = None
        self.processor = None
        if TORCH_AVAILABLE and torch:
            self.device = "cuda" if torch.cuda.is_available() else "cpu"
        else:
            self.device = None
        logger.info(f"Audio embedding generator initialized (device: {self.device})")
    
    def generate_embedding(self, audio_path: Union[str, Path]) -> List[float]:
        """
        Generate embedding for a single audio file
        
        Args:
            audio_path: Path to audio file
            
        Returns:
            Embedding vector as list of floats
        """
        raise NotImplementedError("Subclasses must implement generate_embedding")
    
    def generate_embeddings_batch(self, audio_paths: List[Union[str, Path]]) -> List[List[float]]:
        """
        Generate embeddings for multiple audio files
        
        Args:
            audio_paths: List of audio file paths
            
        Returns:
            List of embedding vectors
        """
        return [self.generate_embedding(audio_path) for audio_path in audio_paths]
    
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of embeddings generated by this model
        
        Returns:
            Embedding dimension
        """
        raise NotImplementedError("Subclasses must implement get_embedding_dimension")


class AudioCLIPEmbeddingGenerator(AudioEmbeddingGenerator):
    """
    AudioCLIP-based audio embedding generator
    
    Uses wav2vec2 as a practical alternative to AudioCLIP for generating
    audio embeddings from clinical voice recordings.
    
    Note: True AudioCLIP requires custom installation. This implementation
    uses wav2vec2 which provides similar functionality and is well-supported.
    """
    
    def __init__(
        self,
        model_name: str = "facebook/wav2vec2-base-960h",
        target_dimension: int = 768
    ):
        """
        Initialize AudioCLIP embedding generator
        
        Args:
            model_name: Audio model name (wav2vec2 as AudioCLIP alternative)
            target_dimension: Target embedding dimension (default: 768 to match Qdrant schema)
        """
        super().__init__(model_name)
        self.target_dimension = target_dimension
        
        if not TORCH_AVAILABLE or not torch or not torchaudio:
            raise ImportError("PyTorch/TorchAudio required. Install with: pip install torch torchaudio")
        
        if not TRANSFORMERS_AVAILABLE:
            raise ImportError("Transformers library required. Install with: pip install transformers")
        
        if not AUDIO_MODEL_AVAILABLE:
            raise ImportError("Audio models required. Install with: pip install transformers torchaudio")
        
        try:
            # Use wav2vec2 as a practical alternative to AudioCLIP
            self.processor = Wav2Vec2Processor.from_pretrained(model_name)
            self.model = Wav2Vec2Model.from_pretrained(model_name)
            self.model.to(self.device)
            self.model.eval()
            logger.info(f"Loaded audio model: {model_name}")
        except Exception as e:
            logger.error(f"Error loading audio model: {e}")
            logger.warning("Falling back to simple embedding method")
            self.model = None
            self.processor = None
    
    def _load_audio(self, audio_path: Union[str, Path]):
        """
        Load audio file and convert to tensor
        
        Args:
            audio_path: Path to audio file
            
        Returns:
            Audio tensor
        """
        if not torchaudio:
            raise ImportError("TorchAudio required for audio loading")
        
        # Load audio file
        waveform, sample_rate = torchaudio.load(str(audio_path))
        
        # Resample to 16kHz if needed (wav2vec2 expects 16kHz)
        if sample_rate != 16000:
            resampler = torchaudio.transforms.Resample(sample_rate, 16000)
            waveform = resampler(waveform)
        
        # Convert to mono if stereo
        if waveform.shape[0] > 1:
            waveform = torch.mean(waveform, dim=0, keepdim=True)
        
        return waveform.squeeze(0)  # Remove channel dimension
    
    def generate_embedding(self, audio_path: Union[str, Path]) -> List[float]:
        """
        Generate embedding for a single audio file using wav2vec2
        
        Args:
            audio_path: Path to audio file
            
        Returns:
            Embedding vector as list of floats (768 dimensions to match Qdrant schema)
        """
        try:
            if self.model and self.processor:
                # Load audio
                waveform = self._load_audio(audio_path)
                
                # Use CLIP model
                with torch.no_grad():
                    # Process audio
                    inputs = self.processor(
                        waveform,
                        sampling_rate=16000,
                        return_tensors="pt",
                        padding=True
                    ).to(self.device)
                    
                    # Generate embedding
                    outputs = self.model(**inputs)
                    
                    # Extract features (use mean pooling of last hidden state)
                    audio_features = outputs.last_hidden_state
                    
                    # Mean pooling across time dimension
                    audio_features = audio_features.mean(dim=1).squeeze()
                    
                    # Project to target dimension if needed
                    if len(audio_features.shape) == 0:
                        # Single value - expand
                        audio_features = audio_features.unsqueeze(0)
                    
                    embedding_dim = audio_features.shape[-1]
                    
                    # Project to target dimension (768) if needed
                    if embedding_dim != self.target_dimension:
                        # Use linear projection or truncate/pad
                        if embedding_dim > self.target_dimension:
                            # Truncate
                            embedding = audio_features[:self.target_dimension]
                        else:
                            # Pad with zeros
                            padding = torch.zeros(self.target_dimension - embedding_dim, device=self.device)
                            embedding = torch.cat([audio_features, padding])
                    else:
                        embedding = audio_features
                    
                    # Normalize
                    embedding = embedding / (embedding.norm(dim=-1, keepdim=True) + 1e-8)
                    
                    # Convert to list
                    if self.device == "cuda":
                        embedding_list = embedding.cpu().numpy().tolist()
                    else:
                        embedding_list = embedding.numpy().tolist()
                    
                    return embedding_list
            else:
                # Fallback: simple hash-based embedding (not recommended for production)
                logger.warning("Using fallback embedding method")
                return self._fallback_embedding(audio_path)
        except Exception as e:
            logger.error(f"Error generating audio embedding: {e}")
            import traceback
            traceback.print_exc()
            # Return zero vector on error
            return [0.0] * self.target_dimension
    
    def _fallback_embedding(self, audio_path: Union[str, Path]) -> List[float]:
        """
        Fallback embedding method (simple hash-based)
        
        Args:
            audio_path: Path to audio file
            
        Returns:
            Simple embedding vector
        """
        # Simple hash-based embedding (not recommended for production)
        import hashlib
        with open(audio_path, 'rb') as f:
            audio_bytes = f.read()
        
        hash_obj = hashlib.sha256(audio_bytes)
        hash_bytes = hash_obj.digest()
        # Convert to float vector
        embedding = [float(b) / 255.0 for b in hash_bytes[:self.target_dimension]]
        # Pad if needed
        while len(embedding) < self.target_dimension:
            embedding.append(0.0)
        return embedding[:self.target_dimension]
    
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of embeddings generated by this model
        
        Returns:
            Embedding dimension (768 to match Qdrant schema)
        """
        return self.target_dimension


# Alias for backward compatibility
AudioEmbeddingGenerator = AudioCLIPEmbeddingGenerator

