"""
Image Embedding Generation Module

Handles image embedding generation using CLIP and other vision models.
"""

import logging
from typing import List, Optional, Union, Dict, Any
from pathlib import Path
import numpy as np

logger = logging.getLogger(__name__)

try:
    from PIL import Image
    PIL_AVAILABLE = True
except ImportError:
    PIL_AVAILABLE = False
    logger.warning("PIL/Pillow not available. Install with: pip install pillow")

try:
    import torch
    import torchvision.transforms as transforms
    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False
    torch = None
    transforms = None
    logger.warning("PyTorch not available. Install with: pip install torch torchvision")

try:
    from transformers import CLIPProcessor, CLIPModel
    CLIP_AVAILABLE = True
except ImportError:
    CLIP_AVAILABLE = False
    logger.warning("CLIP not available. Install with: pip install transformers")


class ImageEmbeddingGenerator:
    """
    Base class for image embedding generation
    """
    
    def __init__(self, model_name: str = "openai/clip-vit-base-patch32"):
        """
        Initialize image embedding generator
        
        Args:
            model_name: Name of the CLIP model to use
        """
        self.model_name = model_name
        self.model = None
        self.processor = None
        if TORCH_AVAILABLE and torch:
            self.device = "cuda" if torch.cuda.is_available() else "cpu"
        else:
            self.device = None
        logger.info(f"Image embedding generator initialized (device: {self.device})")
    
    def generate_embedding(self, image_path: Union[str, Path, Image.Image]) -> List[float]:
        """
        Generate embedding for a single image
        
        Args:
            image_path: Path to image file or PIL Image object
            
        Returns:
            Embedding vector as list of floats
        """
        raise NotImplementedError("Subclasses must implement generate_embedding")
    
    def generate_embeddings_batch(self, image_paths: List[Union[str, Path]]) -> List[List[float]]:
        """
        Generate embeddings for multiple images
        
        Args:
            image_paths: List of image file paths
            
        Returns:
            List of embedding vectors
        """
        return [self.generate_embedding(img_path) for img_path in image_paths]
    
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of embeddings generated by this model
        
        Returns:
            Embedding dimension
        """
        raise NotImplementedError("Subclasses must implement get_embedding_dimension")


class CLIPEmbeddingGenerator(ImageEmbeddingGenerator):
    """
    CLIP-based image embedding generator
    
    Uses CLIP (Contrastive Language-Image Pre-training) for generating
    medical image embeddings (X-rays, lab scans, etc.).
    """
    
    def __init__(
        self,
        model_name: str = "openai/clip-vit-base-patch32"
    ):
        """
        Initialize CLIP embedding generator
        
        Args:
            model_name: CLIP model name
        """
        super().__init__(model_name)
        
        if not PIL_AVAILABLE:
            raise ImportError("PIL/Pillow required. Install with: pip install pillow")
        
        if not TORCH_AVAILABLE or not torch:
            raise ImportError("PyTorch required. Install with: pip install torch torchvision")
        
        if not CLIP_AVAILABLE:
            raise ImportError("CLIP required. Install with: pip install transformers")
        
        try:
            self.model = CLIPModel.from_pretrained(model_name)
            self.processor = CLIPProcessor.from_pretrained(model_name)
            self.model.to(self.device)
            self.model.eval()
            logger.info(f"Loaded CLIP model: {model_name}")
        except Exception as e:
            logger.error(f"Error loading CLIP model: {e}")
            logger.warning("Falling back to simple embedding method")
            self.model = None
            self.processor = None
    
    def _load_image(self, image_path: Union[str, Path, Image.Image]) -> Image.Image:
        """
        Load image from path or return PIL Image
        
        Args:
            image_path: Path to image file or PIL Image object
            
        Returns:
            PIL Image object
        """
        if isinstance(image_path, Image.Image):
            return image_path
        elif isinstance(image_path, (str, Path)):
            return Image.open(image_path)
        else:
            raise ValueError(f"Invalid image path type: {type(image_path)}")
    
    def generate_embedding(self, image_path: Union[str, Path, Image.Image]) -> List[float]:
        """
        Generate embedding for a single image using CLIP
        
        Args:
            image_path: Path to image file or PIL Image object
            
        Returns:
            Embedding vector as list of floats
        """
        try:
            # Load image
            image = self._load_image(image_path)
            
            if self.model and self.processor:
                # Use CLIP model
                with torch.no_grad():
                    # Process image
                    inputs = self.processor(images=image, return_tensors="pt").to(self.device)
                    
                    # Generate embedding
                    image_features = self.model.get_image_features(**inputs)
                    
                    # Normalize
                    image_features = image_features / image_features.norm(dim=-1, keepdim=True)
                    
                    # Convert to list
                    if self.device == "cuda":
                        embedding = image_features.cpu().numpy().tolist()[0]
                    else:
                        embedding = image_features.numpy().tolist()[0]
                    
                    return embedding
            else:
                # Fallback: simple hash-based embedding (not recommended for production)
                logger.warning("Using fallback embedding method")
                return self._fallback_embedding(image)
        except Exception as e:
            logger.error(f"Error generating image embedding: {e}")
            # Return zero vector on error
            dim = self.get_embedding_dimension()
            return [0.0] * dim
    
    def _fallback_embedding(self, image: Image.Image) -> List[float]:
        """
        Fallback embedding method (simple hash-based)
        
        Args:
            image: PIL Image object
            
        Returns:
            Simple embedding vector
        """
        # Simple hash-based embedding (not recommended for production)
        import hashlib
        # Convert image to bytes
        import io
        img_bytes = io.BytesIO()
        image.save(img_bytes, format='PNG')
        img_bytes = img_bytes.getvalue()
        
        hash_obj = hashlib.sha256(img_bytes)
        hash_bytes = hash_obj.digest()
        # Convert to float vector
        embedding = [float(b) / 255.0 for b in hash_bytes[:512]]  # 512-dim vector
        return embedding
    
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of embeddings generated by this model
        
        Returns:
            Embedding dimension
        """
        if self.model:
            try:
                # CLIP vision config hidden size
                dim = self.model.config.vision_config.hidden_size
                # For Qdrant compatibility, we'll project to 768 if needed
                # But return actual dimension for now
                return dim
            except:
                # Try to get from actual embedding
                try:
                    from PIL import Image
                    test_img = Image.new('RGB', (224, 224), color='red')
                    test_emb = self.generate_embedding(test_img)
                    return len(test_emb)
                except:
                    return 512  # Default CLIP dimension
        else:
            return 512  # Fallback dimension


# Alias for backward compatibility
ImageEmbeddingGenerator = CLIPEmbeddingGenerator

