"""
Text Embedding Generation Module

Handles text embedding generation using BioBERT and other medical language models.
"""

import logging
from typing import List, Optional, Union, Dict, Any
import numpy as np

logger = logging.getLogger(__name__)

try:
    import torch
    from transformers import AutoTokenizer, AutoModel
    TRANSFORMERS_AVAILABLE = True
except ImportError:
    TRANSFORMERS_AVAILABLE = False
    torch = None
    logger.warning("Transformers library not available. Install with: pip install transformers torch")

try:
    from sentence_transformers import SentenceTransformer
    SENTENCE_TRANSFORMERS_AVAILABLE = True
except ImportError:
    SENTENCE_TRANSFORMERS_AVAILABLE = False
    logger.warning("Sentence-transformers library not available. Install with: pip install sentence-transformers")


class TextEmbeddingGenerator:
    """
    Base class for text embedding generation
    """
    
    def __init__(self, model_name: str = "dmis-lab/biobert-base-cased-v1.2"):
        """
        Initialize text embedding generator
        
        Args:
            model_name: Name of the model to use (default: BioBERT)
        """
        self.model_name = model_name
        self.model = None
        self.tokenizer = None
        if TRANSFORMERS_AVAILABLE and torch:
            self.device = "cuda" if torch.cuda.is_available() else "cpu"
        else:
            self.device = None
        logger.info(f"Text embedding generator initialized (device: {self.device})")
    
    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate embedding for a single text
        
        Args:
            text: Input text
            
        Returns:
            Embedding vector as list of floats
        """
        raise NotImplementedError("Subclasses must implement generate_embedding")
    
    def generate_embeddings_batch(self, texts: List[str]) -> List[List[float]]:
        """
        Generate embeddings for multiple texts
        
        Args:
            texts: List of input texts
            
        Returns:
            List of embedding vectors
        """
        return [self.generate_embedding(text) for text in texts]
    
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of embeddings generated by this model
        
        Returns:
            Embedding dimension
        """
        raise NotImplementedError("Subclasses must implement get_embedding_dimension")


class BioBERTEmbeddingGenerator(TextEmbeddingGenerator):
    """
    BioBERT-based text embedding generator
    
    Uses BioBERT (Bidirectional Encoder Representations from Transformers for Biomedical Text Mining)
    for generating medical text embeddings.
    """
    
    def __init__(
        self,
        model_name: str = "dmis-lab/biobert-base-cased-v1.2",
        max_length: int = 512,
        use_sentence_transformer: bool = True
    ):
        """
        Initialize BioBERT embedding generator
        
        Args:
            model_name: BioBERT model name
            max_length: Maximum sequence length
            use_sentence_transformer: Whether to use sentence-transformers (simpler API)
        """
        super().__init__(model_name)
        self.max_length = max_length
        self.use_sentence_transformer = use_sentence_transformer and SENTENCE_TRANSFORMERS_AVAILABLE
        
        if not TRANSFORMERS_AVAILABLE:
            raise ImportError(
                "Transformers library required. Install with: pip install transformers torch"
            )
        
        try:
            if self.use_sentence_transformer:
                # Use sentence-transformers for simpler API
                # Try to use a medical model, fallback to BioBERT if not available
                try:
                    self.model = SentenceTransformer('pritamdeka/S-PubMedBert-MS-MARCO')
                    logger.info("Using S-PubMedBert-MS-MARCO for medical text embeddings")
                except Exception:
                    # Fallback to BioBERT via sentence-transformers
                    try:
                        self.model = SentenceTransformer('dmis-lab/biobert-base-cased-v1.2')
                        logger.info("Using BioBERT via sentence-transformers")
                    except Exception:
                        # Final fallback to general model
                        self.model = SentenceTransformer('all-MiniLM-L6-v2')
                        logger.warning("Using general model as fallback. Medical accuracy may be reduced.")
            else:
                # Use transformers library directly
                self.tokenizer = AutoTokenizer.from_pretrained(model_name)
                self.model = AutoModel.from_pretrained(model_name)
                self.model.to(self.device)
                self.model.eval()
                logger.info(f"Loaded BioBERT model: {model_name}")
        except Exception as e:
            logger.error(f"Error loading BioBERT model: {e}")
            logger.warning("Falling back to simple embedding method")
            self.model = None
    
    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate embedding for a single text using BioBERT
        
        Args:
            text: Input text
            
        Returns:
            Embedding vector as list of floats
        """
        if not text or not text.strip():
            # Return zero vector if text is empty
            dim = self.get_embedding_dimension()
            return [0.0] * dim
        
        try:
            if self.use_sentence_transformer and self.model:
                # Use sentence-transformers
                embedding = self.model.encode(text, convert_to_numpy=True)
                return embedding.tolist()
            elif self.model and self.tokenizer:
                # Use transformers library directly
                with torch.no_grad():
                    # Tokenize
                    inputs = self.tokenizer(
                        text,
                        max_length=self.max_length,
                        padding=True,
                        truncation=True,
                        return_tensors="pt"
                    ).to(self.device)
                    
                    # Generate embeddings
                    outputs = self.model(**inputs)
                    
                    # Use mean pooling of last hidden state
                    embeddings = outputs.last_hidden_state.mean(dim=1).squeeze()
                    
                    # Convert to list
                    if self.device == "cuda":
                        embedding = embeddings.cpu().numpy().tolist()
                    else:
                        embedding = embeddings.numpy().tolist()
                    
                    return embedding
            else:
                # Fallback: simple TF-IDF-like embedding (not recommended for production)
                logger.warning("Using fallback embedding method")
                return self._fallback_embedding(text)
        except Exception as e:
            logger.error(f"Error generating embedding: {e}")
            # Return zero vector on error
            dim = self.get_embedding_dimension()
            return [0.0] * dim
    
    def _fallback_embedding(self, text: str) -> List[float]:
        """
        Fallback embedding method (simple hash-based)
        
        Args:
            text: Input text
            
        Returns:
            Simple embedding vector
        """
        # Simple hash-based embedding (not recommended for production)
        import hashlib
        hash_obj = hashlib.sha256(text.encode())
        hash_bytes = hash_obj.digest()
        # Convert to float vector
        embedding = [float(b) / 255.0 for b in hash_bytes[:384]]  # 384-dim vector
        return embedding
    
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of embeddings generated by this model
        
        Returns:
            Embedding dimension
        """
        if self.use_sentence_transformer and self.model:
            # Get dimension from model
            return self.model.get_sentence_embedding_dimension()
        elif self.model:
            # Get dimension from model config
            try:
                return self.model.config.hidden_size
            except:
                return 768  # Default BioBERT dimension
        else:
            return 384  # Fallback dimension


# Alias for backward compatibility
TextEmbeddingGenerator = BioBERTEmbeddingGenerator

