"""
RAG-Based Clinical Insight Generation

Combines retrieved context from Qdrant with LLM reasoning to generate
context-aware clinical insights and recommendations.
"""

import logging
import json
import os
from typing import List, Dict, Any, Optional, Union
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import Enum

from src.retrieval import CaseRetriever, RetrievalResult, RetrievalOptions, RetrievalMode
from src.models import Case, CaseMetadata

logger = logging.getLogger(__name__)

# LLM Provider Support - Google Gemini
try:
    import google.generativeai as genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False
    logger.warning("Google Generative AI library not available. Install with: pip install google-generativeai")


class LLMProvider(Enum):
    """Supported LLM providers"""
    GEMINI = "gemini"


@dataclass
class Recommendation:
    """Clinical recommendation"""
    type: str  # "diagnosis", "treatment", "test", "monitoring", "referral"
    title: str
    description: str
    confidence: float  # 0.0 to 1.0
    evidence: List[str] = field(default_factory=list)  # Supporting evidence
    citations: List[str] = field(default_factory=list)  # Case IDs or source URLs
    priority: str = "medium"  # "high", "medium", "low"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return asdict(self)


@dataclass
class ClinicalInsight:
    """Clinical insight generated by RAG"""
    query_case_id: Optional[str] = None
    query_text: Optional[str] = None
    retrieved_cases: List[Dict[str, Any]] = field(default_factory=list)
    differential_diagnoses: List[Dict[str, str]] = field(default_factory=list)  # [{"diagnosis": "...", "confidence": "..."}]
    recommendations: List[Recommendation] = field(default_factory=list)
    summary: Optional[str] = None
    confidence_score: Optional[float] = None
    reasoning_chain: List[str] = field(default_factory=list)
    citations: List[str] = field(default_factory=list)
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        data = asdict(self)
        # Convert datetime to ISO format
        if isinstance(data.get("generated_at"), datetime):
            data["generated_at"] = data["generated_at"].isoformat()
        # Convert recommendations
        data["recommendations"] = [rec.to_dict() for rec in self.recommendations]
        return data


@dataclass
class RAGOptions:
    """Options for RAG-based insight generation"""
    # Retrieval options
    retrieval_limit: int = 5
    retrieval_mode: RetrievalMode = RetrievalMode.HYBRID
    retrieval_filters: Optional[Dict[str, Any]] = None
    
    # LLM options
    llm_provider: LLMProvider = LLMProvider.GEMINI
    llm_model: str = "gemini-2.5-flash"  # Fast and cost-effective. Alternatives: "gemini-2.5-pro-preview-03-25", "gemini-1.5-pro"
    temperature: float = 0.3  # Lower for more deterministic medical responses
    max_tokens: int = 2000
    
    # Prompt options
    include_similar_cases: bool = True
    include_knowledge_base: bool = True
    include_medical_entities: bool = True
    include_outcomes: bool = True
    
    # Output options
    generate_differential_diagnoses: bool = True
    generate_recommendations: bool = True
    generate_summary: bool = True
    include_reasoning: bool = True


class ClinicalRAG:
    """
    RAG-based Clinical Insight Generator
    
    Features:
    - Context retrieval from Qdrant
    - LLM integration for clinical reasoning
    - Structured insight generation
    - Recommendation generation with citations
    - Explainable recommendations
    """
    
    def __init__(
        self,
        case_retriever: CaseRetriever,
        llm_provider: LLMProvider = LLMProvider.GEMINI,
        llm_model: str = "gemini-2.5-flash",
        api_key: Optional[str] = None
    ):
        """
        Initialize clinical RAG system
        
        Args:
            case_retriever: CaseRetriever instance for retrieving similar cases
            llm_provider: LLM provider to use (currently only GEMINI supported)
            llm_model: Gemini model name (e.g., "gemini-2.5-flash", "gemini-2.5-pro-preview-03-25", "gemini-1.5-pro")
            api_key: Optional API key (if not provided, uses GOOGLE_API_KEY environment variable)
        """
        self.case_retriever = case_retriever
        self.llm_provider = llm_provider
        self.llm_model = llm_model
        self.api_key = api_key or self._get_api_key()
        
        # Initialize Gemini client
        self.llm_client = self._initialize_llm_client()
        
        logger.info(f"Clinical RAG initialized with {llm_provider.value} ({llm_model})")
    
    def _get_api_key(self) -> Optional[str]:
        """Get API key from environment"""
        if self.llm_provider == LLMProvider.GEMINI:
            return os.getenv("GOOGLE_API_KEY")
        return None
    
    def _initialize_llm_client(self):
        """Initialize Gemini client"""
        if self.llm_provider != LLMProvider.GEMINI:
            raise ValueError(f"Only Gemini provider is supported. Got: {self.llm_provider}")
        
        if not GEMINI_AVAILABLE:
            raise ImportError("Google Generative AI library required. Install with: pip install google-generativeai")
        
        if not self.api_key:
            raise ValueError("GOOGLE_API_KEY environment variable required")
        
        # Configure Gemini API
        genai.configure(api_key=self.api_key)
        
        # Return the model instance
        return genai.GenerativeModel(self.llm_model)
    
    def generate_insights(
        self,
        query_text: str,
        query_image_path: Optional[str] = None,
        query_case: Optional[Case] = None,
        options: Optional[RAGOptions] = None
    ) -> ClinicalInsight:
        """
        Generate clinical insights using RAG
        
        Args:
            query_text: Query text (symptoms, patient description, etc.)
            query_image_path: Optional query image path
            query_case: Optional full case object
            options: Optional RAG options
            
        Returns:
            ClinicalInsight object with recommendations and reasoning
        """
        options = options or RAGOptions()
        
        try:
            # Step 1: Retrieve similar cases
            logger.info("Retrieving similar cases...")
            retrieval_options = RetrievalOptions(
                limit=options.retrieval_limit,
                mode=options.retrieval_mode,
            )
            if options.retrieval_filters:
                # Apply custom filters
                for key, value in options.retrieval_filters.items():
                    setattr(retrieval_options, key, value)
            
            retrieved_results = self.case_retriever.retrieve_similar_cases(
                query_text=query_text,
                query_image_path=query_image_path,
                options=retrieval_options
            )
            
            logger.info(f"Retrieved {len(retrieved_results)} similar cases")
            
            # Step 2: Format context for LLM
            context = self._format_context(
                query_text=query_text,
                query_case=query_case,
                retrieved_results=retrieved_results,
                options=options
            )
            
            # Step 3: Generate prompt
            prompt = self._build_prompt(
                query_text=query_text,
                query_case=query_case,
                context=context,
                options=options
            )
            
            # Step 4: Call LLM
            logger.info(f"Calling LLM ({self.llm_provider.value}/{self.llm_model})...")
            llm_response = self._call_llm(prompt, options)
            
            # Step 5: Parse LLM response
            insight = self._parse_llm_response(
                llm_response=llm_response,
                query_text=query_text,
                query_case=query_case,
                retrieved_results=retrieved_results,
                options=options
            )
            
            logger.info("Clinical insights generated successfully")
            return insight
            
        except Exception as e:
            logger.error(f"Error generating clinical insights: {e}")
            raise
    
    def _format_context(
        self,
        query_text: str,
        query_case: Optional[Case],
        retrieved_results: List[RetrievalResult],
        options: RAGOptions
    ) -> str:
        """Format retrieved context for LLM input"""
        context_parts = []
        
        # Add query case information
        if query_case:
            context_parts.append("=== CURRENT CASE ===")
            context_parts.append(f"Patient ID: {query_case.patient_id}")
            if query_case.metadata:
                context_parts.append(f"Age Group: {query_case.metadata.age_group}")
                context_parts.append(f"Region: {query_case.metadata.region}")
                context_parts.append(f"Comorbidities: {', '.join(query_case.metadata.comorbidities)}")
            if query_case.modalities.get("text"):
                text_modality = query_case.modalities["text"]
                if isinstance(text_modality, dict):
                    transcript = text_modality.get("content", {}).get("transcript", "")
                else:
                    transcript = text_modality.content.get("transcript", "") if hasattr(text_modality, 'content') else ""
                if transcript:
                    context_parts.append(f"Transcript: {transcript}")
            context_parts.append("")
        
        # Add patient history summary if patient_id is available
        if query_case and query_case.patient_id:
            patient_history_summary = self._retrieve_patient_history_summary(
                query_case.patient_id,
                query_text,
                options
            )
            if patient_history_summary:
                context_parts.append("=== PATIENT HISTORY SUMMARY ===")
                context_parts.append(patient_history_summary)
                context_parts.append("")
        
        # Add similar cases
        if options.include_similar_cases and retrieved_results:
            context_parts.append("=== SIMILAR PAST CASES ===")
            for i, result in enumerate(retrieved_results, 1):
                context_parts.append(f"\n--- Similar Case {i} (Similarity: {result.score:.3f}) ---")
                
                if result.metadata:
                    context_parts.append(f"Age Group: {result.metadata.age_group}")
                    context_parts.append(f"Region: {result.metadata.region}")
                    if result.metadata.comorbidities:
                        context_parts.append(f"Comorbidities: {', '.join(result.metadata.comorbidities)}")
                    if result.metadata.diagnosis:
                        context_parts.append(f"Diagnosis: {result.metadata.diagnosis}")
                    if options.include_outcomes and result.metadata.outcome:
                        context_parts.append(f"Outcome: {result.metadata.outcome}")
                
                if result.modalities.get("text"):
                    transcript = result.modalities["text"].get("transcript", "")
                    if transcript:
                        context_parts.append(f"Transcript: {transcript[:500]}...")  # Truncate long transcripts
                
                if options.include_medical_entities and result.case_data.get("medical_entities"):
                    entities = result.case_data.get("medical_entities", [])
                    entity_summary = ", ".join([f"{e.get('text', '')} ({e.get('entity_type', '')})" for e in entities[:10]])
                    if entity_summary:
                        context_parts.append(f"Medical Entities: {entity_summary}")
                
                context_parts.append("")
        
        return "\n".join(context_parts)
    
    def _retrieve_patient_history_summary(
        self,
        patient_id: str,
        query_text: str,
        options: RAGOptions
    ) -> str:
        """Retrieve and summarize patient history from patient_memory_collection"""
        try:
            import os
            from src.storage.qdrant_storage import QdrantStorage
            from src.embeddings import BioBERTEmbeddingGenerator
            
            # Connect to patient_memory_collection
            qdrant_url = os.getenv("QDRANT_URL")
            if qdrant_url:
                patient_storage = QdrantStorage(
                    url=qdrant_url,
                    api_key=os.getenv("QDRANT_API_KEY"),
                    collection_name="patient_memory_collection",
                    vector_size=768
                )
            else:
                patient_storage = QdrantStorage(
                    host=os.getenv("QDRANT_HOST", "localhost"),
                    port=int(os.getenv("QDRANT_PORT", "6334")),
                    api_key=os.getenv("QDRANT_API_KEY"),
                    collection_name="patient_memory_collection",
                    vector_size=768
                )
            
            # Generate query embedding
            embedder = BioBERTEmbeddingGenerator()
            query_embedding = embedder.generate_embedding(query_text[:500])
            
            # Search for patient records
            filters = {"patient_id": patient_id} if patient_id else None
            patient_results = patient_storage.search_with_filters(
                query_embedding=query_embedding,
                filters=filters,
                limit=5,
                score_threshold=0.3
            )
            
            if not patient_results:
                return ""
            
            # Summarize patient history
            history_parts = []
            for i, result in enumerate(patient_results[:5], 1):  # Limit to top 5
                payload = result.get("payload", {})
                content = payload.get("transcript", "") or payload.get("content", "") or payload.get("text", "")
                
                if content:
                    metadata_info = []
                    if payload.get("diagnosis"):
                        metadata_info.append(f"Diagnosis: {payload.get('diagnosis')}")
                    if payload.get("age_group"):
                        metadata_info.append(f"Age: {payload.get('age_group')}")
                    if payload.get("comorbidities"):
                        comorbidities = payload.get("comorbidities")
                        if isinstance(comorbidities, list):
                            metadata_info.append(f"Comorbidities: {', '.join(comorbidities)}")
                        elif comorbidities:
                            metadata_info.append(f"Comorbidities: {comorbidities}")
                    
                    history_entry = f"Visit {i}"
                    if metadata_info:
                        history_entry += f" ({'; '.join(metadata_info)})"
                    history_entry += f": {content[:200]}..."
                    
                    history_parts.append(history_entry)
            
            if history_parts:
                return "\n".join(history_parts)
            
            return ""
            
        except Exception as e:
            logger.warning(f"Error retrieving patient history summary: {e}")
            return ""
    
    def _build_prompt(
        self,
        query_text: str,
        query_case: Optional[Case],
        context: str,
        options: RAGOptions
    ) -> str:
        """Build prompt for LLM"""
        prompt_parts = []
        
        # System prompt
        prompt_parts.append("You are a clinical decision support system. Your role is to analyze patient cases and provide evidence-based clinical insights.")
        prompt_parts.append("")
        prompt_parts.append("IMPORTANT GUIDELINES:")
        prompt_parts.append("- Base your recommendations on the retrieved similar cases and medical knowledge")
        prompt_parts.append("- Provide differential diagnoses with confidence levels")
        prompt_parts.append("- Suggest appropriate diagnostic tests, treatments, and monitoring")
        prompt_parts.append("- Cite specific similar cases that influenced your reasoning")
        prompt_parts.append("- Always emphasize that recommendations should be reviewed by qualified healthcare professionals")
        prompt_parts.append("- Do not provide definitive diagnoses, only differential diagnoses")
        prompt_parts.append("")
        
        # Context
        prompt_parts.append("=== CONTEXT ===")
        prompt_parts.append(context)
        prompt_parts.append("")
        
        # Query
        prompt_parts.append("=== CURRENT CASE QUERY ===")
        prompt_parts.append(query_text)
        prompt_parts.append("")
        
        # Instructions
        prompt_parts.append("=== TASK ===")
        prompt_parts.append("Based on the context above, provide clinical insights for the current case.")
        prompt_parts.append("")
        
        if options.generate_differential_diagnoses:
            prompt_parts.append("1. Provide a list of differential diagnoses with confidence levels (0.0 to 1.0)")
        
        if options.generate_recommendations:
            prompt_parts.append("2. Provide clinical recommendations including:")
            prompt_parts.append("   - Diagnostic tests to consider")
            prompt_parts.append("   - Treatment options")
            prompt_parts.append("   - Monitoring suggestions")
            prompt_parts.append("   - Referral considerations")
        
        if options.generate_summary:
            prompt_parts.append("3. Provide a brief clinical summary")
        
        if options.include_reasoning:
            prompt_parts.append("4. Explain your reasoning, citing specific similar cases")
        
        prompt_parts.append("")
        prompt_parts.append("Format your response as JSON with the following structure:")
        prompt_parts.append('{')
        prompt_parts.append('  "differential_diagnoses": [{"diagnosis": "...", "confidence": 0.0-1.0}],')
        prompt_parts.append('  "recommendations": [{"type": "diagnosis|treatment|test|monitoring|referral", "title": "...", "description": "...", "confidence": 0.0-1.0, "priority": "high|medium|low", "citations": ["case_id_1", "case_id_2"]}],')
        prompt_parts.append('  "summary": "...",')
        prompt_parts.append('  "reasoning_chain": ["step1", "step2", ...],')
        prompt_parts.append('  "confidence_score": 0.0-1.0')
        prompt_parts.append('}')
        
        return "\n".join(prompt_parts)
    
    def _call_llm(self, prompt: str, options: RAGOptions) -> str:
        """Call Gemini API"""
        try:
            if self.llm_provider != LLMProvider.GEMINI:
                raise ValueError(f"Only Gemini provider is supported. Got: {self.llm_provider}")
            
            # Build the full prompt with system instructions
            full_prompt = f"""You are a clinical decision support system. Always respond with valid JSON.

{prompt}"""

            # Configure generation parameters
            from google.generativeai import types
            generation_config = types.GenerationConfig(
                temperature=options.temperature,
                max_output_tokens=options.max_tokens,
                response_mime_type="application/json"  # Request JSON response
            )
            
            # Generate content
            response = self.llm_client.generate_content(
                full_prompt,
                generation_config=generation_config
            )
            
            # Extract text from response
            if response.text:
                return response.text
            else:
                raise ValueError("Empty response from Gemini API")
                
        except Exception as e:
            logger.error(f"Error calling Gemini API: {e}")
            raise
    
    def _parse_llm_response(
        self,
        llm_response: str,
        query_text: str,
        query_case: Optional[Case],
        retrieved_results: List[RetrievalResult],
        options: RAGOptions
    ) -> ClinicalInsight:
        """Parse LLM response into ClinicalInsight object"""
        try:
            # Extract JSON from response (handle markdown code blocks)
            response_text = llm_response.strip()
            if response_text.startswith("```json"):
                response_text = response_text[7:]
            if response_text.startswith("```"):
                response_text = response_text[3:]
            if response_text.endswith("```"):
                response_text = response_text[:-3]
            response_text = response_text.strip()
            
            # Parse JSON
            parsed = json.loads(response_text)
            
            # Extract differential diagnoses
            differential_diagnoses = []
            if options.generate_differential_diagnoses:
                for diag in parsed.get("differential_diagnoses", []):
                    differential_diagnoses.append({
                        "diagnosis": diag.get("diagnosis", ""),
                        "confidence": float(diag.get("confidence", 0.0))
                    })
            
            # Extract recommendations
            recommendations = []
            if options.generate_recommendations:
                for rec in parsed.get("recommendations", []):
                    recommendation = Recommendation(
                        type=rec.get("type", "treatment"),
                        title=rec.get("title", ""),
                        description=rec.get("description", ""),
                        confidence=float(rec.get("confidence", 0.0)),
                        evidence=rec.get("evidence", []),
                        citations=rec.get("citations", []),
                        priority=rec.get("priority", "medium")
                    )
                    recommendations.append(recommendation)
            
            # Extract other fields
            summary = parsed.get("summary", "") if options.generate_summary else None
            reasoning_chain = parsed.get("reasoning_chain", []) if options.include_reasoning else []
            confidence_score = float(parsed.get("confidence_score", 0.0)) if parsed.get("confidence_score") else None
            
            # Collect citations from recommendations
            citations = []
            for rec in recommendations:
                citations.extend(rec.citations)
            citations = list(set(citations))  # Remove duplicates
            
            # Format retrieved cases for insight
            retrieved_cases = []
            for result in retrieved_results:
                retrieved_cases.append({
                    "case_id": result.case_id,
                    "score": result.score,
                    "diagnosis": result.metadata.diagnosis if result.metadata else None,
                    "outcome": result.metadata.outcome if result.metadata else None,
                })
            
            # Create insight
            insight = ClinicalInsight(
                query_case_id=query_case.case_id if query_case else None,
                query_text=query_text,
                retrieved_cases=retrieved_cases,
                differential_diagnoses=differential_diagnoses,
                recommendations=recommendations,
                summary=summary,
                confidence_score=confidence_score,
                reasoning_chain=reasoning_chain,
                citations=citations
            )
            
            return insight
            
        except json.JSONDecodeError as e:
            logger.error(f"Error parsing LLM JSON response: {e}")
            logger.error(f"Response: {llm_response[:500]}")
            # Return fallback insight
            return ClinicalInsight(
                query_text=query_text,
                summary="Error parsing LLM response. Please review the raw response.",
                confidence_score=0.0
            )
        except Exception as e:
            logger.error(f"Error parsing LLM response: {e}")
            raise
    
    def generate_recommendations(
        self,
        query_text: str,
        query_case: Optional[Case] = None,
        options: Optional[RAGOptions] = None
    ) -> List[Recommendation]:
        """
        Generate clinical recommendations only
        
        Args:
            query_text: Query text
            query_case: Optional case object
            options: Optional RAG options
            
        Returns:
            List of recommendations
        """
        insight = self.generate_insights(query_text, query_case=query_case, options=options)
        return insight.recommendations
    
    def generate_differential_diagnoses(
        self,
        query_text: str,
        query_case: Optional[Case] = None,
        options: Optional[RAGOptions] = None
    ) -> List[Dict[str, Any]]:
        """
        Generate differential diagnoses only
        
        Args:
            query_text: Query text
            query_case: Optional case object
            options: Optional RAG options
            
        Returns:
            List of differential diagnoses with confidence scores
        """
        insight = self.generate_insights(query_text, query_case=query_case, options=options)
        return insight.differential_diagnoses

